List<Map<String, dynamic>> userList = [
    {
      "name": "Jose",
      "image": "https://api.dicebear.com/7.x/adventurer/png?seed=Jose",
      "date": "2026-04-20",
      "time": "10:30 AM",
      "status": "pending",
    },
    {
      "name": "Akhil",
      "image": "https://api.dicebear.com/7.x/adventurer/png?seed=Akhil",
      "date": "2026-04-21",
      "time": "11:15 AM",
      "status": "approved",
    },
    {
      "name": "Ravi",
      "image": "https://api.dicebear.com/7.x/adventurer/png?seed=Ravi",
      "date": "2026-04-22",
      "time": "09:45 AM",
      "status": "rejected",
    },
    {
      "name": "User 4",
      "image": "https://api.dicebear.com/7.x/adventurer/png?seed=Sneha",
      "date": "2026-04-23",
      "time": "02:00 PM",
      "status": "pending",
    },
    {
      "name": "User 5",
      "image": "https://api.dicebear.com/7.x/adventurer/png?seed=Anjali",
      "date": "2026-04-24",
      "time": "03:20 PM",
      "status": "approved",
    },
    {
      "name": "User 6",
      "image": "https://api.dicebear.com/7.x/adventurer/png?seed=Rahul",
      "date": "2026-04-25",
      "time": "04:10 PM",
      "status": "pending",
    },
    {
      "name": "User 7",
      "image": "https://api.dicebear.com/7.x/adventurer/png?seed=Meena",
      "date": "2026-04-26",
      "time": "05:45 PM",
      "status": "approved",
    },
    {
      "name": "User 8",
      "image": "https://api.dicebear.com/7.x/adventurer/png?seed=Kiran",
      "date": "2026-04-27",
      "time": "08:30 AM",
      "status": "rejected",
    },
    {
      "name": "User 9",
      "image": "https://api.dicebear.com/7.x/adventurer/png?seed=Divya",
      "date": "2026-04-28",
      "time": "12:00 PM",
      "status": "pending",
    },
    {
      "name": "User 10",
      "image": "https://api.dicebear.com/7.x/adventurer/png?seed=Arjun",
      "date": "2026-04-29",
      "time": "06:15 PM",
      "status": "approved",
    },
  ];